[[CURRENCIES]]
code = "TFT_BR"
issuer = "GDHK7BEVVO7NTV2WZHZRV7Y7NJKVR6Z5BQ4YL2KB2XOYQMAMATVDZUSY"
display_decimals = 2
name = "Threefold 3bot Browser Project"
desc = "Personal browser running close to our 3bot"
image = "https://www.threefold.io/assets/3fold_icon.png"

