[[CURRENCIES]]
code = "TFT3F"
issuer = "GDLCTAG5ECTX4MLOPC5ZVTSNMOJ56KV5LERL2ZDUOMYGHW7I6ERRPTKX"
display_decimals = 2
name = "Threefold 3bot Files Project"
desc = "Our personal cloud on the TF Grid"
image = "https://www.threefold.io/assets/3fold_icon.png"

