[[CURRENCIES]]
code = "TFT_VR"
issuer = "GAEAESVWVH2FAQHQK4DMWE6HSWRJFRFGRUNQR7KY6KR42XZHFBBHHEPZ"
display_decimals = 2
name = "Threefold Virtual Reality Museum Project"
desc = "Virtual reality museum online of 500.000 artworks as part of TF Grid"
image = "https://www.threefold.io/assets/3fold_icon.png"

