[[CURRENCIES]]
code = "TFT_TB"
issuer = "GAKNUHLTV7LFSDZFUVNTFPB34VVGJS6PKOXD5FS4Z5TKNWQ3FYII7I6U"
display_decimals = 2
name = "Threefold TimeBank Project"
desc = "World first global time token, on top of TF Grid, +200k users today"
image = "https://www.threefold.io/assets/3fold_icon.png"

