[[CURRENCIES]]
code = "TFT"
issuer = "GA47YZA3PKFUZMPLQ3B5F2E3CJIB57TGGU7SPCQT2WAEYKN766PWIMB3"
display_decimals = 2
name = "ThreeFold Token"
desc = "A digital currency used to buy autonomous and decentralized Internet services (compute, storage, and application) on the ThreeFold Network"
image = "https://www2.threefold.io/assets/3fold_icon.png"

[[CURRENCIES]]
code = "TFTA"
issuer = "GB55A4RR4G2MIORJTQA4L6FENZU7K4W7ATGY6YOT2CW47M5SZYGYKSCT"
display_decimals = 2
name = "ThreeFold Token"
desc = "A digital currency used to buy autonomous and decentralized Internet services (compute, storage, and application) on the ThreeFold Network"
image = "https://www2.threefold.io/assets/3fold_icon.png"

[[CURRENCIES]]
code = "FreeTFT"
issuer = "GBLDUINEFYTF7XEE7YNWA3JQS4K2VD37YU7I2YAE7R5AHZDKQXSS2J6R"
display_decimals = 2
name = "Free ThreeFold Token"
desc = "A free digital currency used to buy free autonomous and decentralized Internet services (compute, storage, and application) on the ThreeFold Network"
image = "https://www.threefold.io/assets/3fold_icon.png"

[[CURRENCIES]]
code = "TFT_FD"
issuer = "GB437RSTO5UQ67CXI2EHB3Q64LV4WZTPLGJ34KFVYK4INSXQXV4FUESI"
display_decimals = 2
name = "Threefold TF Foundation Project"
desc = "Foundation funding (marketing, operations team, grid roll out, roadshows, …)"
image = "https://www.threefold.io/assets/3fold_icon.png"

[[CURRENCIES]]
code = "TFT_3B"
issuer = "GDXK3HPD5IXKGIYEOXE57XYIOBJ7RFU66JMZ7Q3BZJ4TZELL65O5P3WX"
display_decimals = 2
name = "Threefold 3bot (Digital Twin)Project"
desc = "80% of our digital life implemented on top of the 3bot"
image = "https://www.threefold.io/assets/3fold_icon.png"

[[CURRENCIES]]
code = "TFT_GE"
issuer = "GDSZ7WIH3BAQ6L5ISYMUO57SDWRYZVILVYH2EBBZSOQLVBAHIIQ3TRQX"
display_decimals = 2
name = "Threefold TF Grid enhancements Project"
desc = "Further improvements to the grid as sponsored by the TF Foundation"
image = "https://www.threefold.io/assets/3fold_icon.png"

[[CURRENCIES]]
code = "TFT_3O"
issuer = "GC5H3QPTETKPW5UZXLRMMP54M3JTVINPEGIP6I246KOO7IWSXZISY53F"
display_decimals = 2
name = "Threefold 3bot Office Project"
desc = "100% compatible office suite running on top of your 3bot"
image = "https://www.threefold.io/assets/3fold_icon.png"

[[CURRENCIES]]
code = "TFT_CL"
issuer = "GBV5ZGJEWVJI5CUFNKOT7G4ZLAQOZSXVBOZMQBD6U6OWDLAWKNO662VF"
display_decimals = 2
name = "Threefold Crystal Language Project"
desc = "Core language used to implement the 3bot and future SDK for ThreeFold"
image = "https://www.threefold.io/assets/3fold_icon.png"

[[CURRENCIES]]
code = "TFT_EDU"
issuer = "GD6YVKYYSOH445GRVMFSBZKH3KL43EJQPVZIU4NKNW7VFO4H752EMMFG"
display_decimals = 2
name = "Threefold P2P Education Project"
desc = "World’s first true peer-to-peer education system on top of TF Grid"
image = "https://www.threefold.io/assets/3fold_icon.png"

[[CURRENCIES]]
code = "TFT_BR"
issuer = "GDHK7BEVVO7NTV2WZHZRV7Y7NJKVR6Z5BQ4YL2KB2XOYQMAMATVDZUSY"
display_decimals = 2
name = "Threefold 3bot Browser Project"
desc = "Personal browser running close to our 3bot"
image = "https://www.threefold.io/assets/3fold_icon.png"

[[CURRENCIES]]
code = "TFT_3F"
issuer = "GCBQ37WUJD4VWS2LCS2QSESPQFNTBPN4BSDNUH6WAYSRZ3NO5SFHTEAA"
display_decimals = 2
name = "Threefold 3bot Files Project"
desc = "Our personal cloud on the TF Grid"
image = "https://www.threefold.io/assets/3fold_icon.png"

[[CURRENCIES]]
code = "TFT_GS"
issuer = "GDHEDZROXDU3WALUAIQUZQORB3FIR5EJDV2QPHCOD376OQTO75YA3SKG"
display_decimals = 2
name = "Threefold TF Grid Solutions Project"
desc = "Open source solutions ported to the grid"
image = "https://www.threefold.io/assets/3fold_icon.png"

[[CURRENCIES]]
code = "TFT_FC"
issuer = "GCCKI7BIIYGHXMKDZBVX5Y6EEYOS3CPMNPBGJVTZLEK7ZC2WQHXAXWUA"
display_decimals = 2
name = "Threefold FreeFlow connect Project"
desc = "Peer-to-peer video conferencing"
image = "https://www.threefold.io/assets/3fold_icon.png"

[[CURRENCIES]]
code = "TFT_MA"
issuer = "GDL37OMXH4PUGSQOHL6SNHVNR7WPQKXAGI3GLRUYTURKVGUUDYWHCPMB"
display_decimals = 2
name = "Threefold 3bot Marketing / Prod mgmt Project"
desc = "Bring the 3bot alive as a digital twin"
image = "https://www.threefold.io/assets/3fold_icon.png"

[[CURRENCIES]]
code = "TFT_SM"
issuer = "GCZIGT2XDARJYDDE72EOTNRVTYYIGM5CW4KSEB3OSL7J4YDSR3IDERRG"
display_decimals = 2
name = "Threefold Social Media / Collaboration Project"
desc = "Combination of social media / productivity & collaboration tools"
image = "https://www.threefold.io/assets/3fold_icon.png"

[[CURRENCIES]]
code = "TFT_UI"
issuer = "GDG44AEQHFJR35HINIFCXTJCEPJ5LPKPMR447GXI3PI62IBEQJZYOZMV"
display_decimals = 2
name = "Threefold TF Grid User Interface Project"
desc = "Easy-to-use interface to provision IT workloads on the grid"
image = "https://www.threefold.io/assets/3fold_icon.png"

[[CURRENCIES]]
code = "TFT_VR"
issuer = "GAEAESVWVH2FAQHQK4DMWE6HSWRJFRFGRUNQR7KY6KR42XZHFBBHHEPZ"
display_decimals = 2
name = "Threefold Virtual Reality Museum Project"
desc = "Virtual reality museum online of 500.000 artworks as part of TF Grid"
image = "https://www.threefold.io/assets/3fold_icon.png"

[[CURRENCIES]]
code = "TFT_TB"
issuer = "GDXUM7H3HKQKOOF2YVOWGP7YQWBKM7LUPWFSYSP3P4LFZCIOB2LFEJAL"
display_decimals = 2
name = "Threefold TimeBank Project"
desc = "World first global time token, on top of TF Grid, +200k users today"
image = "https://www.threefold.io/assets/3fold_icon.png"

