[[CURRENCIES]]
code="TFT"
issuer="GA47YZA3PKFUZMPLQ3B5F2E3CJIB57TGGU7SPCQT2WAEYKN766PWIMB3"
display_decimals=2 
name="ThreeFold Token"
desc="A decentralized digital currency used to buy autonomous and decentralized Internet services (compute, storage, and application) on the ThreeFold Network"
image="https://www2.threefold.io/assets/3fold_icon.png"