[[CURRENCIES]]
code = "TFT_TB"
issuer = "GDXUM7H3HKQKOOF2YVOWGP7YQWBKM7LUPWFSYSP3P4LFZCIOB2LFEJAL"
display_decimals = 2
name = "Threefold TimeBank Project"
desc = "World first global time token, on top of TF Grid, +200k users today"
image = "https://www.threefold.io/assets/3fold_icon.png"

