[[CURRENCIES]]
code = "TFTSM"
issuer = "GCZIGT2XDARJYDDE72EOTNRVTYYIGM5CW4KSEB3OSL7J4YDSR3IDERRG"
display_decimals = 2
name = "Threefold Social Media / Collaboration Project"
desc = "Combination of social media / productivity & collaboration tools"
image = "https://www.threefold.io/assets/3fold_icon.png"

