[[CURRENCIES]]
code = "TFTSM"
issuer = "GATPWDG2T7JTRV3AYFU5FUWSEVZOLQRH6POG5F2CYETNQZ6FSIKAXLBP"
display_decimals = 2
name = "Threefold Social Media / Collaboration Project"
desc = "Combination of social media / productivity & collaboration tools"
image = "https://www.threefold.io/assets/3fold_icon.png"

