[[CURRENCIES]]
code = "TFT_3O"
issuer = "GC7VVHXKHPM2YOQW3PM46PYQF3IBTHSLVVBNWAR4SZMWOFVVKZNXHCAA"
display_decimals = 2
name = "Threefold 3bot Office Project"
desc = "100% compatible office suite running on top of your 3bot"
image = "https://www.threefold.io/assets/3fold_icon.png"

